version: '2'
services:
  redis:
    image: redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
  mongodb:
    image: tutum/mongodb
    command: mongod --smallfiles
    volumes:
      - mongodb:/data/db
    ports:
    - "27017:27017"

volumes:
  redis:
    driver: "local"
  mongodb:
    driver: "local"
